language: python

python: 
  - "2.7"
  - "3.4"

# Setup miniconda

sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --set ssl_verify false
  - conda info -a
install:
  - conda install python=$TRAVIS_PYTHON_VERSION networkx=1.10
  - conda install pip setuptools nose
  - pip install -U coveralls
  - python setup.py install
script: 
  - nosetests --with-coverage --cover-package=cliquetree --logging-level=INFO
  - coveralls
